<a href="https://colab.research.google.com/github/bcguilherme/Insurance-Charges-Prediction-API-with-Automated-Machine-Learning-using-PyCaret-/blob/main/insurance_autoML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import pandas as pd
from pycaret.regression import *

In [ ]:
FEATURES = ['age', 'bmi', 'children', 'smoker']
TARGET = 'charges'

In [ ]:
data = pd.read_csv('../data/insurance.csv')
data = data[[*FEATURES,TARGET]]
data

      age     bmi  children smoker      charges
0      19  27.900         0    yes  16884.92400
1      18  33.770         1     no   1725.55230
2      28  33.000         3     no   4449.46200
3      33  22.705         0     no  21984.47061
4      32  28.880         0     no   3866.85520
...   ...     ...       ...    ...          ...
1333   50  30.970         3     no  10600.54830
1334   18  31.920         0     no   2205.98080
1335   18  36.850         0     no   1629.83350
1336   21  25.800         0     no   2007.94500
1337   61  29.070         0    yes  29141.36030

[1338 rows x 5 columns]

In [ ]:
s = setup(data, target='charges', silent=True, session_id=2023)

In [ ]:
best_model = compare_models()

In [ ]:
best_model

GradientBoostingRegressor(alpha=0.9, ccp_alpha=0.0, criterion='friedman_mse',
                          init=None, learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=100,
                          n_iter_no_change=None, presort='deprecated',
                          random_state=2023, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [ ]:
tuned_model = tune_model(best_model, fold=5, n_iter=100)

In [ ]:
evaluate_model(tuned_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'paramâ€¦

In [ ]:
final_model = finalize_model(tuned_model)

In [ ]:
os.makedirs('../app', exist_ok=True)
create_api(final_model, '../app/api_insurance')

API sucessfully created. This function only creates a POST API, it doesn't run it automatically.

To run your API, please run this command --> !python ../app/api_insurance.py